### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by rwols**
There is no good distribution for this language server.
We could do a combination of `git clone depth=1` and `git submodule init`. But this seemed easier.

### CODE REVIEW

**Comment by rchl** [comment]
The `log` directory you can probably remove (and gitignore)?

**Comment by rchl** [comment]
Would it be possible to move all server files into a subdirectory? It looks a bit messy with server and package files mixed like that.

**Comment by rchl** [comment]
Also could mention where the server code is coming from in the README.

Maybe also include instructions on how to update the server because even if you've done it now, not sure if you are gonna remember in few months how it was done and what changes were necessary to make it work. :)

**Comment by rwols** [comment]
> Would it be possible to move all server files into a subdirectory? It looks a bit messy with server and package files mixed like that.

I tried this, but this server is really picky about its file structure.

**Pull request merged**
